version: '3.9'
services:

  sav_database:
    image: mysql
    container_name: sav_database
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sav
    volumes:
      - mysqldb:/var/lib/mysql

volumes:
  mysqldb:
    driver: local